// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x12( // Layer 0 (Sywnt Keyboard Layout)
		KC_LCTL, LT(4,KC_APP), LT(8,QK_GESC), LT(12,KC_EQL), LT(14,KC_MINS), KC_TAB, KC_BSPC, KC_S, KC_Y, KC_N, KC_W, RCTL_T(KC_T),
		KC_LSFT, LT(3,KC_LBRC), LT(7,KC_RBRC), LT(11,KC_QUOT), KC_A, KC_U, KC_O, KC_C, KC_F, KC_K, KC_G, RSFT_T(KC_M),
		KC_LALT, LT(2,KC_BSLS), LT(6,KC_SLSH), LT(10,KC_SCLN), KC_I, KC_E, KC_B, KC_D, KC_H, KC_J, KC_L, RALT_T(KC_P),
		KC_LGUI, LT(1,TO(0)), LT(5,KC_CAPS), LT(9,KC_COMM), LT(13,KC_DOT), KC_SPC, KC_ENT, KC_Q, KC_R, KC_V, KC_X, RGUI_T(KC_Z)
	),
	[1] = LAYOUT_ortho_4x12( // Layer 1 (Number & Fn Keys)
		KC_LCTL, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_F10, KC_F11, KC_F12, KC_F22, KC_F23, KC_F24,
		KC_LSFT, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_F7, KC_F8, KC_F9, KC_F19, KC_F20, KC_F21,
		KC_LALT, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_F4, KC_F5, KC_F6, KC_F16, KC_F17, KC_F18,
		KC_LGUI, TO(0), KC_NO, KC_0, KC_GRV, KC_NO, KC_F1, KC_F2, KC_F3, KC_F13, KC_F14, KC_F15
	),
	[2] = LAYOUT_ortho_4x12( // Layer 2 (Keypad, Arrow Keys & Homekey)
		KC_LCTL, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_NUM, KC_NO, KC_SCRL, KC_PSCR, KC_NO, KC_HOME,
		KC_LSFT, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_PAST, KC_PSLS, KC_NO, KC_UP, KC_NO, KC_PGUP,
		KC_LALT, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_PPLS, KC_PMNS, KC_LEFT, KC_DOWN,
		KC_RGHT, KC_PGDN, KC_LGUI, TO(0), KC_NO, KC_P0, KC_PDOT, KC_PCMM, KC_PEQL, KC_PENT, KC_PAUS, KC_INS, KC_DEL, KC_END
	),
	[3] = LAYOUT_ortho_4x12( // Layer 3 (US ANSI Shifted Symbols Keys)
		KC_LCTL, KC_NO, KC_NO, KC_AMPR, KC_ASTR, KC_LPRN, KC_PIPE, KC_QUES, KC_DQUO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_DLR, KC_PERC, KC_CIRC, KC_LT, KC_GT, KC_COLN, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_PLUS, KC_LCBR, KC_RCBR, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_RPRN, KC_TILD, KC_NO, KC_UNDS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[4] = LAYOUT_ortho_4x12( // Layer 4 (Application Keys)
		KC_LCTL, KC_NO, KC_NO, KC_COPY, KC_PSTE, KC_FIND, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_AGIN, KC_UNDO, KC_CUT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_MENU, KC_SLCT, KC_STOP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_HELP, KC_EXEC, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCAP, KC_LNUM, KC_LSCR
	),
	[5] = LAYOUT_ortho_4x12( // Layer 5 (Multimedia Keys)
		KC_LCTL, KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_VOLD, KC_VOLU, KC_MRWD, KC_MFFD, KC_NO, KC_NO, KC_PWR,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_MSTP, KC_MUTE, KC_MPLY, KC_EJCT, KC_NO, KC_NO, KC_NO, KC_SLEP,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WAKE,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[6] = LAYOUT_ortho_4x12( // Layer 6 (Mouse Keys)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL0, KC_NO, KC_NO, KC_BTN4, KC_BTN3, KC_BTN5, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL1, KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL2, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_NO, KC_WH_U, KC_WH_R
	),
	[7] = LAYOUT_ortho_4x12( // Layer 7 (Shortcut Layer for …)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[8] = LAYOUT_ortho_4x12( // Layer 8 (UNICODE Key)
		KC_LCTL, KC_NO, KC_NO, UC(0x2019), UC(0x201D), UC(0x2026), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[9] = LAYOUT_ortho_4x12( // Layer 9 (Shortcut Layer for …)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[10] = LAYOUT_ortho_4x12( // Layer 10 (Shortcut Layer for …)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[11] = LAYOUT_ortho_4x12( // Layer 11 (Shortcut Layer for …)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[12] = LAYOUT_ortho_4x12( // # Layer 12 (Shortcut Layer for …)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[13] = LAYOUT_ortho_4x12( // Layer 13 (Shortcut Layer for …)
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
	[14] = LAYOUT_ortho_4x12( // Layer 14 (UNICODE Mode and QMK Key)
		KC_LCTL, KC_NO, KC_NO, KC_NO, UC_NEXT, UC_PREV, UC_MAC, UC_LINX, UC_WIN, UC_BSD, UC_WINC, UC_EMAC,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LGUI, TO(0), KC_NO, KC_NO, EE_CLR, QK_BOOT, QK_RBT, DB_TOGG, KC_NO, KC_NO, KC_NO, QK_MAKE
	),
	[15] = LAYOUT_ortho_4x12( // Layer 15 (Keyboard Layer Navigation)
		KC_LCTL, KC_NO, KC_NO, KC_NO, DF(12), DF(13), DF(14), DF(15), TO(12), TO(13), TO(14), TO(15),
		KC_LSFT, KC_NO, KC_NO, KC_NO, DF(8), DF(9), DF(10), DF(11), TO(9), TO(8), TO(10), TO(11),
		KC_LALT, KC_NO, KC_NO, KC_NO, DF(4), DF(5), DF(6), DF(7), TO(4), TO(5), TO(6), TO(7),
		KC_LGUI, TO(0), KC_NO, KC_NO, DF(0), DF(1), DF(2), DF(3), TO(0), TO(1), TO(2), TO(3)
	)
};
